# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('comments', models.CharField(blank=True, max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('lob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Lob')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Version'),
        ),
    ]
